### POST add
POST https://kc-demo-sample-app.azurewebsites.net/add
Content-Type: application/json

{
  "value": 1
}

### GET get
GET https://kc-demo-sample-app.azurewebsites.net/get
Content-Type: application/json
